#ifndef _CF_APPLICATIONEXT_IDL_
#define _CF_APPLICATIONEXT_IDL_

#include "ossie/CF/cf.idl"

module ExtendedCF {

	interface ApplicationExt : CF::Application {
		CF::Resource reset(in string compInstId) raises(CF::LifeCycle::ReleaseError, CF::ExecutableDevice::ExecuteFail);
		CF::Resource launch(in string usageName, in string instID, in CF::Properties execParams, in string spdURI, in string implID) raises (CF::ExecutableDevice::ExecuteFail);
	};
	
};

#endif