#ifndef _CF_APPLICATIONEXT_IDL_
#define _CF_APPLICATIONEXT_IDL_

#include "ossie/CF/cf.idl"

module ExtendedCF {
	// This module represents internal API not to be used outside the debug plugin.
	interface ApplicationExt : CF::Application {
		CF::Resource reset(in string compInstId) raises(CF::LifeCycle::ReleaseError, CF::ExecutableDevice::ExecuteFail);
		CF::Resource launch(in string id, in CF::Properties execParams, in string spdURI, in string implID, in string mode) raises (CF::ExecutableDevice::ExecuteFail);
	};
};

#endif
