#ifndef __AGGREGATEDEVICES_DEFINED
#define __AGGREGATEDEVICES_DEFINED
/* It appears that OMNIOrb, nor the standard CORBA C++ mapping
   supports a single server implementation that inherits from
   multiple skeleton classes (although other ORBs appear to 
   allow this).  As a work-around, define the multiple inheritence
   in the IDL.
*/
#include "ossie/CF/cf.idl"

/* These are SCA CoreFramework extensions provided by OSSIE
*/
module CF {
  interface AggregatePlainDevice : CF::Device, CF::AggregateDevice
  {};

  interface AggregateLoadableDevice : CF::LoadableDevice, CF::AggregateDevice
  {};

  interface AggregateExecutableDevice : CF::ExecutableDevice, CF::AggregateDevice
  {};
};
#endif
