//Source file: PortTypes.idl
#ifndef __PORTTYPES_DEFINED
#define __PORTTYPES_DEFINED
module PortTypes {
    /* This type is a unbounded sequence of booleans. */
    typedef sequence <boolean> BooleanSequence;
    /* This type is a unbounded sequence of characters. */
    typedef sequence <char> CharSequence;
    /* This type is a unbounded sequence of doubles. */
    typedef sequence <double> DoubleSequence;
    /* This type is a unbounded sequence of longlongs. */
    typedef sequence <long long> LongLongSequence;
    /* This type is a unbounded sequence of longs. */
    typedef sequence <long> LongSequence;
    /* This type is a unbounded sequence of shorts. */
    typedef sequence <short> ShortSequence;
    /* This type is a unbounded sequence of unsigned long longs. */
    typedef sequence <unsigned long long> UlongLongSequence;
    /* This type is a unbounded sequence of unsigned longs. */
    typedef sequence <unsigned long> UlongSequence;
    /* This type is a unbounded sequence of unsigned shorts. */
    typedef sequence <unsigned short> UshortSequence;
    /* This type is a unbounded sequence of floats. */
    typedef sequence <float> FloatSequence;
};
#endif
