
#ifndef _QUERYABLE_PORT_IDL_
#define _QUERYABLE_PORT_IDL_

#include "ossie/CF/cf.idl"

module ExtendedCF {

    struct UsesConnection {
        string connectionId;
        Object port;
    };

    typedef sequence<UsesConnection> UsesConnectionSequence;

    // The QueryablePort interface extends the standard CF::Port so that
    // the list of current connections can be queried.
    interface QueryablePort : CF::Port {
        readonly attribute UsesConnectionSequence connections;
    };
};

#endif
