/* Generated By:JavaCC: Do not edit this line. MFileParserConstants.java */
package gov.redhawk.mfile.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface MFileParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT_2 = 7;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT_2 = 10;
  /** RegularExpression Id. */
  int FUNCTION = 11;
  /** RegularExpression Id. */
  int NL = 19;
  /** RegularExpression Id. */
  int ID = 20;
  /** RegularExpression Id. */
  int DECIMALINT = 21;
  /** RegularExpression Id. */
  int FIXED_PT = 22;
  /** RegularExpression Id. */
  int HEXADECIMALINT = 23;
  /** RegularExpression Id. */
  int FLOATONE = 24;
  /** RegularExpression Id. */
  int FLOATTWO = 25;
  /** RegularExpression Id. */
  int CHARACTER = 26;
  /** RegularExpression Id. */
  int STRING = 27;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT_2 = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "\"%}\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"#}\"",
    "<token of kind 8>",
    "<SINGLE_LINE_COMMENT>",
    "<SINGLE_LINE_COMMENT_2>",
    "\"function\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\";\"",
    "<NL>",
    "<ID>",
    "<DECIMALINT>",
    "<FIXED_PT>",
    "<HEXADECIMALINT>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<CHARACTER>",
    "<STRING>",
  };

}
