/* Generated By:JavaCC: Do not edit this line. MFileParserConstants.java */
package gov.redhawk.mfile.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MFileParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int FUNCTION = 10;
  /** RegularExpression Id. */
  int ID = 18;
  /** RegularExpression Id. */
  int OCTALINT = 19;
  /** RegularExpression Id. */
  int DECIMALINT = 20;
  /** RegularExpression Id. */
  int FIXED_PT = 21;
  /** RegularExpression Id. */
  int HEXADECIMALINT = 22;
  /** RegularExpression Id. */
  int FLOATONE = 23;
  /** RegularExpression Id. */
  int FLOATTWO = 24;
  /** RegularExpression Id. */
  int CHARACTER = 25;
  /** RegularExpression Id. */
  int STRING = 26;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"%{\"",
    "\"%}\"",
    "<token of kind 9>",
    "\"function\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "<ID>",
    "<OCTALINT>",
    "<DECIMALINT>",
    "<FIXED_PT>",
    "<HEXADECIMALINT>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<CHARACTER>",
    "<STRING>",
  };

}
